spring:
  application:
    name: cuoco
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  swagger-ui:
    path: /swagger-ui
jwt:
  secret: ${JWT_SECRET}
gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}
  image:
    url: ${GEMINI_IMAGE_URL}
  temperature: ${GEMINI_TEMPERATURE}
shared:
  plan:
    free:
      max-recipes: ${FREE_MAX_RECIPES}
    premium:
      max-recipes: ${PREMIUM_MAX_RECIPES}