spring:
  application:
    name: cuoco
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  swagger-ui:
    path: /swagger-ui
jwt:
  secret: ${JWT_SECRET}
gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}
  image:
    url: ${GEMINI_IMAGE_URL}
  temperature: ${GEMINI_TEMPERATURE}
shared:
  recipes:
    size:
      free: ${FREE_USER_RECIPES_SIZE:3}
      pro: ${PRO_USER_RECIPES_DEFAULT_SIZE:5}
    images:
      base-path: ${RECIPE_IMAGES_BASE_PATH}
  meal-preps:
    size: ${MEAL_PREP_DEFAULT_SIZE:1}
    recipes-size: ${RECIPES_SIZE_PER_MEAL_PREP:3}