spring:
  application:
    name: cuoco
  datasource:
    url: jdbc:mysql://localhost:3306/cuoco?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
jwt:
  secret: defaultsecretkeyforjwtauth123456

gemini:
  api:
    key: AIzaSyAV7UuOjd7BfbEC8XGOu358hQ7CbOjwpHs
