spring:
  application:
    name: cuoco
  datasource:
    url: jdbc:mysql://localhost:3306/cuoco?serverTimezone=UTC
    username: root
    password: suser123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
jwt:
  secret: defaultsecretkeyforjwtauth123456

gemini:
  api:
    key: AIzaSyCJbW7Frv2QVg08Az242DH5m6219iHU37E
