spring:
  application:
    name: cuoco
  datasource:
    url: jdbc:mysql://localhost:3306/cuoco?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
jwt:
  secret: defaultsecretkeyforjwtauth123456
gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent?key=
    key: AIzaSyCJbW7Frv2QVg08Az242DH5m6219iHU37E
  temperature: 0.4
