spring:
  application:
    name: planicocina
  datasource:
    url: jdbc:mysql://localhost:3306/planicocina?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
jwt:
  secret: defaultsecretkeyforjwtauth123456
