spring:
  application:
    name: cuoco
  datasource:
    url: jdbc:mysql://localhost:3306/cuoco?serverTimezone=UTC
    username: root
    password: Tomas.1995
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  swagger-ui:
    path: /swagger-ui
jwt:
  secret: defaultsecretkeyforjwtauth123456
gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent?key=
    key: AIzaSyCJbW7Frv2QVg08Az242DH5m6219iHU37E
  temperature: 0.4
shared:
  plan:
    free:
      max-recipes: 3
    premium:
      max-recipes: 5