spring:
  application:
    name: cuoco
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  swagger-ui:
    path: /swagger-ui
jwt:
  secret: ${JWT_SECRET}
gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}
  image:
    url: ${GEMINI_IMAGE_URL}
  temperature: ${GEMINI_TEMPERATURE}
email:
  host: ${EMAIL_HOST:smtp.gmail.com}
  port: ${EMAIL_PORT:587}
  username: ${EMAIL_USERNAME:cuoco.8bits@gmail.com}
  password: ${EMAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
shared:
  email:
    no-reply:
      name: ${NO_REPLY_NAME:Cuoco}
      from: ${NO_REPLY_EMAIL:noresponder@cuoco.com.ar}
    notification:
      name: ${NOTIFICATION_NAME:Cuoco}
      from: ${NOTIFICATION_EMAIL:notifications@cuoco.com.ar}
  recipes:
    size:
      free: ${FREE_USER_RECIPES_SIZE:3}
      pro: ${PRO_USER_RECIPES_DEFAULT_SIZE:5}
    images:
      base-path: ${RECIPE_IMAGES_BASE_PATH}
  meal-preps:
    size: ${MEAL_PREP_DEFAULT_SIZE:1}
    recipes-size: ${RECIPES_SIZE_PER_MEAL_PREP:3}