name: Build validation

on:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build project
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            ./gradlew build -x test -Pspring.profiles.active=prod
          else
            ./gradlew build -x test -Pspring.profiles.active=dev
          fi
